Repository bpr3p/devdayz_secret_project, pull requests merged in 2019-06, with the labels that each got.

#17 fix(Teams) [CR] Make sure that teams are sent to Firebase.
  app/controllers/teams_controller.rb
  app/models/team.rb
Labels: :shipit:, bug

#18 feat(Timer) [BR]: Add timer to pictionary
  app/javascript/react/containers/WordsIndexContainer.js
Labels: enhancement

#25 Collapsible word lists and random style fixes
  app/assets/stylesheets/clues.scss
  app/assets/stylesheets/foundation_and_overrides.scss
  app/controllers/clues_controller.rb
  app/views/clues/index.html.erb
  app/views/clues/new.html.erb
  app/views/years/index.html.erb
Labels: enhancement

#26 Firebase fixes [CR, NM]
  app/controllers/events_controller.rb
  app/controllers/teams_controller.rb
  app/models/event.rb
  app/models/firebase/api.rb
  app/models/firebase/event.rb
  app/models/firebase/team.rb
  app/models/team.rb
  app/views/events/edit.html.erb
  app/views/events/index.html.erb
  app/views/events/show.html.erb
  app/views/teams/index.html.erb
  app/views/teams/show.html.erb
Labels: :shipit:, bug, enhancement

#28 Br categories
  app/assets/stylesheets/clues.scss
  app/controllers/api/v1/clues_controller.rb
  app/controllers/categories_controller.rb
  app/controllers/clues_controller.rb
  app/controllers/difficulties_controller.rb
  app/javascript/react/components/CategoryComponent.js
  app/javascript/react/containers/WordsIndexContainer.js
  app/models/category.rb
  app/models/clue.rb
  app/models/difficulty.rb
  app/models/year.rb
  app/views/categories/edit.html.erb
  app/views/categories/index.html.erb
  app/views/categories/new.html.erb
  app/views/categories/show.html.erb
  app/views/clues/edit.html.erb
  app/views/clues/index.html.erb
  app/views/clues/new.html.erb
  app/views/clues/show.html.erb
  app/views/difficulties/edit.html.erb
  app/views/difficulties/index.html.erb
  app/views/difficulties/new.html.erb
  app/views/difficulties/show.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  db/migrate/20190620234259_change_difficulties_to_categories.rb
  db/migrate/20190621000207_update_clues_table.rb
  db/migrate/20190621011203_add_year_to_category.rb
  db/migrate/20190622143649_remove_difficulty_and_update_categories.rb
  db/schema.rb
  db/seeds.rb
Labels: draft
