Repository bpr3p/devdayz_secret_project, pull requests merged in 2019-05, with the labels that each got.

#4 feat(Scoreboard)[CR] Scoreboard first pass
  Gemfile
  Gemfile.lock
  app/controllers/events_controller.rb
  app/controllers/teams_controller.rb
  app/models/score.rb
  app/models/team.rb
  app/models/year.rb
  app/views/events/index.html.erb
  app/views/events/new.html.erb
  app/views/events/show.html.erb
  app/views/teams/index.html.erb
  app/views/teams/new.html.erb
  app/views/teams/show.html.erb
  config/routes.rb
  db/migrate/20190419182921_create_year_table.rb
  db/migrate/20190419192249_add_year_to_event.rb
  db/schema.rb
  package-lock.json
Labels: enhancement

#3 feat(Admin)[NI]: Admin section
  app/assets/javascripts/admin.js
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/application.css
  app/assets/stylesheets/home.scss
  app/assets/stylesheets/maps.scss
  app/controllers/admin_controller.rb
  app/controllers/api/v1/admin_controller.rb
  app/controllers/api/v1/maps_controller.rb
  app/controllers/application_controller.rb
  app/controllers/clues_controller.rb
  app/controllers/games_controller.rb
  app/controllers/homes_controller.rb
  app/controllers/maps_controller.rb
  app/helpers/admin_helper.rb
  app/javascript/react/components/WordTile.js
  app/javascript/react/components/app.js
  app/javascript/react/containers/AdminContainer.js
  app/javascript/react/containers/MapsContainer.js
  app/views/admin/index.html.erb
  app/views/homes/index.html.erb
  app/views/layouts/application.html.erb
  app/views/maps/index.html.erb
  config/initializers/assets.rb
  config/routes.rb
  db/migrate/20190308195739_create_maps.rb
  package-lock.json
  package.json
  spec/controllers/admin_controller_spec.rb
  spec/helpers/admin_helper_spec.rb
  yarn.lock
Labels: enhancement

#11 Firebase
  Gemfile
  Gemfile.lock
  app/controllers/scores_controller.rb
  app/controllers/teams_controller.rb
  app/models/event.rb
  app/models/firebase/api.rb
  app/models/firebase/event.rb
  app/models/firebase/team.rb
  app/models/score.rb
  app/models/team.rb
  app/views/events/show.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  db/migrate/20190517155913_add_event_firebase_id.rb
  db/schema.rb
  package-lock.json
Labels: :shipit:, enhancement

#12 Ni teams
  Gemfile
  Gemfile.lock
  app/assets/javascripts/admin.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/teams.scss
  app/controllers/teams_controller.rb
  app/views/maps/index.html.erb
  app/views/teams/index.html.erb
  app/views/teams/new.html.erb
  app/views/teams/show.html.erb
  db/seeds.rb
Labels: :shipit:, enhancement

#14 Br pictionary2
  .DS_Store
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/clues.scss
  app/assets/stylesheets/years.scss
  app/javascript/react/components/WordTile.js
  app/javascript/react/containers/WordsIndexContainer.js
  app/views/clues/index.html.erb
  app/views/events/index.html.erb
  app/views/years/index.html.erb
  db/schema.rb
Labels: :shipit:

#15 Ni cleanup stuff
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/years.scss
  app/controllers/events_controller.rb
  app/javascript/react/containers/MapsContainer.js
  app/javascript/react/containers/WordsIndexContainer.js
  app/views/clues/index.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/events/index.html.erb
  app/views/events/new.html.erb
  app/views/events/show.html.erb
  app/views/games/index.html.erb
  app/views/layouts/application.html.erb
  app/views/teams/index.html.erb
  app/views/teams/new.html.erb
  app/views/teams/show.html.erb
  app/views/years/index.html.erb
  app/views/years/new.html.erb
  app/views/years/show.html.erb
  db/seeds.rb
Labels: :shipit:
